
detectors:
  DuplicateMethodCall:
    enabled: false
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  MissingSafeMethod:
    enabled: false
  LongParameterList:
    enabled: false
  UtilityFunction:
    enabled: false
  NestedIterators: 
    enabled: false
  UncommunicativeMethodName:
    enabled: false  
  Attribute:
    enabled: false        
  BooleanParameter:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  NilCheck:
    enabled: false
  TooManyMethods:
    enabled: false
  RepeatedConditional:
    enabled: false
  ControlParameter:
    enabled: false