name: Code Analysis and Compliance Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - staging

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3' 
          bundler-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev 

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run Brakeman
        run: bundle exec brakeman --no-exit-on-warn --format plain
      - name: Run RuboCop
        run: bundle exec rubocop
      - name: Run Reek
        run: bundle exec reek
      - name: Run Bundler-Audit
        run: bundle exec bundler-audit check --update
