name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  staging-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libxml2-dev \
            libxslt1-dev \
            build-essential

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3' 
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Capistrano Deploy
        run: STAGE=staging bundle exec cap staging deploy

